#ifndef YAKVC_H
#define YAKVC_H

/* Generated by `cargo xtask header`. Do not edit by hand. */

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

/**
 * Version of this C ABI. Java refuses to use a library whose version differs
 * from the one it was built against. Bump on any incompatible change.
 */
#define YAKVC_ABI_VERSION 1

/**
 * Returns [`YAKVC_ABI_VERSION`]. Safe to call before anything else.
 */
uint32_t yakvc_abi_version(void);

#endif  /* YAKVC_H */
